### ISSUE TITLE
Please, consider to specify a license

### ISSUE THREAD

**Issue by ifraixedes** [kpwn/iOSRE#12]
First of all, thanks to release this work on a public repository.

Nonetheless, this repo doesn't have any concrete license (or it isn't easy to see), so I would like that you consider to choose one to avoid the confusion that it causes with its absence, the work has applied the default copyright laws which the most of the people we aren't sure the implications because we aren't lawyers.

[This page may help you to decide which one is more convenient for you and all the benefits that an open license has over a closed one](https://help.github.com/articles/open-source-licensing/), however, don't get me wrong, choose the one that fits better to your specific case, independently if it's open or not.

Thanks for considering.

**Comment by argp** [comment]
lol

**Comment by Naville** [comment]
Funny. How can we choose a license if it's contributed by sooo many people

**Comment by ifraixedes** [comment]
Ask the contributors and choose one which they are happy; future contributions should agree with the license.

In my opinion it's better to do that than defaulting to the laws, that the most of us, we don't know and in my case I don't exactly understand, however you're free to do what you want.

**Comment by kpwn** [comment]
Hey,
I've added a LICENSE.txt file. Any opinion?

**Comment by ifraixedes** [comment]
For me looks ok, because I'm clear what I could do with this without hiring a lawyer.

**Comment by Naville** [comment]
WTF License is that ROFLMFAO

**Comment by mstg** [comment]
10/10 license

**Comment by Azure-Agst** [comment]
"In the event that you happen to make a zillion bucks off of
this, then good for you; _consider buying a homeless person a meal._" DEAD LMAO

**Comment by Naville** [comment]
someone please close this issue
