### ISSUE TITLE
Shall we provide Mach-O Samples as companion to that wiki page?

### ISSUE THREAD

**Issue by Naville** [kpwn/iOSRE#18]
And. Come to think about it, JLevin already wrote a nice article about Mach-O

**Comment by kpwn** [comment]
I'm okay with supplying samples of Mach-Os. We could probably also base the Mach-O thing on his article, too. By the way, do you like how I reformatted the page?

**Comment by Naville** [comment]
Much better than my messy words.
I guess native speakers are better at this kind of stuff.
btw for some LC types ,well, most. I didn't see any Mach-O containing them. So that will be a trouble
Also. not related but I think we should change to discord instead of IRC

**Comment by kpwn** [comment]
I like IRC personally. I will look out for samples.

**Comment by Naville** [comment]
I do have samples but they are Apple Copyright binaries....
Uploading them here would results in a DMCA Takedown

**Comment by kpwn** [comment]
I think supplying mach_headers and zeroing all non-interesting data (eg code or symbols or data) would constitute fair use. 
So for instance, a Mach-O sample for demonstrating LC_CODE_SIGNATURE would have everything but cs blob and mach header zeroed.

note: IANAL.

**Comment by Naville** [comment]
Me neither.
The second question is that this would (apparently) increase Repo size.
Eventually the whole thing's size would be unacceptable.

Or. We can give instructions of retrieving these binaries instead of the binary itself?

**Comment by kpwn** [comment]
If the binaries contain many zeroes compression will be extremely efficient on them.

**Comment by Naville** [comment]
Gr8t.
Problem Solved
