### ISSUE TITLE
Is it better to store papers separately?

### ISSUE THREAD

**Issue by Naville** [kpwn/iOSRE#28]
Like mega?

The size of the repo is growing fast

**Comment by Naville** [comment]
Tried add my own collection using this method.
See https://github.com/kpwn/iOSRE/blob/master/Papers/README.md

Need discussion about that though

**Comment by jndok** [comment]
yeah, I thought about this too. The repo size will get way too big if we keep stuffing in papers. We should move everything to an external mirror, and possibly remove copies of the same slides/papers

**Comment by Naville** [comment]
Well. Rebase everyone's copy to clean revision history would be a huge mess.

I'd say what's done is done, but we shall update further papers in external links.

What do you say?

**Comment by Naville** [comment]
No more reply so.......
Deal.
Closed
