### ISSUE TITLE
Question about KPP

### ISSUE THREAD

**Issue by Fadi5555** [kpwn/iOSRE#31]
hi there. My question is the new jailbreak will defeat KPP? I mean not avoid it like pangu9.
Because this is so important to implement JIT to 64-bit device. Last time about having JIT support on 64-bit devices was on ios 8.4 (by TaiG).
Anyway do you have any idea or plan how to defeat or patch KPP please?
Thanks for everything.

**Comment by Naville** [comment]
Nobody showed (at least in public) how to defeat KPP now, not to mention share the method.
Current jailbreaks are bypassing it instead of defeat ot

**Comment by Naville** [comment]
And issues is not the place for asking such questions. /r/jailbreak is probably better for that

**Comment by Naville** [comment]
I personally doubt such method would be released even if exists.
