### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by kmddd59** [kpwn/iOSRE#36]
`The following build commands failed:
	Ld build/Release/class-dump normal x86_64
	GenerateDSYMFile build/Release/class-dump.dSYM build/Release/class-dump
	Ld build/Release/deprotect normal x86_64
	GenerateDSYMFile build/Release/deprotect.dSYM build/Release/deprotect
	Ld build/Release/formatType normal x86_64
	GenerateDSYMFile build/Release/formatType.dSYM build/Release/formatType
(6 failures)
mv: rename ./class-dump/build/Release/class-dump to /usr/local/bin/class-dump: No such file or directory
Wades-MacBook-Air-3:Install Commonly Used Utilities timfarris$ 
`

**Comment by Naville** [comment]
Seems like an issue on class-dump 's side. Can anyone replicate this error?
