### ISSUE TITLE
Is adding links to a free beginner's RE book encouraged?

### ISSUE THREAD

**Issue by Naville** [kpwn/iOSRE#38]
I've just added @iosre 's  free book to PAPERS.md in commit 68e3b519486defa24fd276755b65bd91ce338b4e

However:
While the version we are sharing here is freely distributed, the second version is not, so is this somehow a commercial behavior and is discouraged in this repo?
And this book is for complete beginners so shall we mix it with all the other cutting edge stuff

**Comment by NicholasLAranda** [comment]
If it's not copyrighted, I'd say share all the knowledge you have.
